### ISSUE TITLE
lastest updated error 7.0

### ISSUE THREAD

**Issue by GhostLone93** [vice-grip/starsector-mod-emergent-threats#1]
102628 [Thread-2] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.RuntimeException: Ship hull spec [vice_incursion_base] not found!
java.lang.RuntimeException: Ship hull spec [vice_incursion_base] not found!
	at com.fs.starfarer.loading.do.o00000(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.loading.SpecStore.o00000(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.loading.SpecStore.o00000(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.loading.ShipHullSpecLoader.new(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.loading.ShipHullSpecLoader.Ó00000(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.loading.SpecStore.ÓO0000(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.loading.ResourceLoaderState.init(Unknown Source) ~[port_obf.jar:?]
	at com.fs.state.AppDriver.begin(Unknown Source) ~[port.common_obf.jar:?]
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.StarfarerLauncher.super(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source) ~[port_obf.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]
	
	I used solution proposed on forum of the mod and it didnt work, I'm copy pasting error  here.

**Comment by vice-grip** [comment]
I'm pretty sure this is due to loading a pre-v0.7.0 game, since the Incursion got renamed to the Intrepid at that time.
