### ISSUE TITLE
Freeport docking CTD

### ISSUE THREAD

**Issue by Bucketsmith** [vice-grip/starsector-mod-emergent-threats#3]
```
205428: 2092231 [Thread-2] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.NullPointerException: Cannot invoke "com.fs.starfarer.api.campaign.FactionAPI.getId()" because "this.selFaction" is null
205429: java.lang.NullPointerException: Cannot invoke "com.fs.starfarer.api.campaign.FactionAPI.getId()" because "this.selFaction" is null
205430: 	at data.scripts.world.submarkets.EndGameStoreXIVMarket.updateCargoPrePlayerInteraction(EndGameStoreXIVMarket.java:136) ~[?:?]
205431: 	at data.scripts.vice.listeners.PruneBantengMarketListener.pruneMarket(PruneBantengMarketListener.java:44) ~[?:?]
205432: 	at data.scripts.vice.listeners.PruneBantengMarketListener.reportPlayerOpenedMarket(PruneBantengMarketListener.java:50) ~[?:?]
205433: 	at com.fs.starfarer.campaign.CampaignEngine.reportPlayerOpenedMarket(Unknown Source) ~[port_obf.jar:?]
205434: 	at com.fs.starfarer.campaign.CampaignState.startEncounterInvolvingPlayerFleet(Unknown Source) ~[port_obf.jar:?]
205435: 	at com.fs.starfarer.campaign.BaseLocation.advance(Unknown Source) ~[port_obf.jar:?]
205436: 	at com.fs.starfarer.campaign.StarSystem.advance(Unknown Source) ~[port_obf.jar:?]
205437: 	at com.fs.starfarer.campaign.CampaignEngine.advance(Unknown Source) ~[port_obf.jar:?]
205438: 	at com.fs.starfarer.campaign.CampaignState.advance(Unknown Source) ~[port_obf.jar:?]
205439: 	at com.fs.starfarer.BaseGameState.traverse(Unknown Source) ~[port_obf.jar:?]
205440: 	at com.fs.state.AppDriver.begin(Unknown Source) ~[port.common_obf.jar:?]
205441: 	at com.fs.starfarer.combat.CombatMain.main(Unknown Source) [port_obf.jar:?]
205442: 	at com.fs.starfarer.StarfarerLauncher.super(Unknown Source) [port_obf.jar:?]
205443: 	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source) [port_obf.jar:?]
205444: 	at java.base/java.lang.Thread.run(Thread.java:1447) [?:?]
```

When trying to dock at the Freeport.
I've got a commission with the Sindrian Fuel Company, if that matters?
Since it's complaining about faction being null.

**Comment by Bucketsmith** [comment]
I've done some digging in another direction and it's a problem with another mod. (Extra Submarkets)
Sorry man!

**Comment by vice-grip** [comment]
Yeah it looks like something going on with EndGameStoreXIVMarket. I hope you manage to figure it out.
